USE GRN
GO

/****** Object:  StoredProcedure [dbo].[AWLI_TL_Suss_WithHldng_Config]    Script Date: 25/2/2021 15:18:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







ALTER PROCEDURE[dbo].[AWLI_TL_Suss_WithHldng_Config] @StartDate CHAR(10), @EndDate CHAR(10), @ArchSUSS integer
AS

BEGIN
	IF @ArchSUSS = 1 
	BEGIN
		SELECT	'2004' + -- AS FORMULARIO 
				'0100' + -- AS VERSION +
				REPLICATE(' ',10) + --AS CODIGO_TRAZABILIDAD +
			--	'9012345678' +
				SUBSTRING(CMP.TAXREGTN,1,11) + --CUIT_AGENTE +
				substring(Rg.nfRET_Regimen,1,charindex('-',Rg.nfRET_Regimen)-1)  + --AS IMPUESTO,
				substring(Rg.nfRET_Regimen,charindex('-',Rg.nfRET_Regimen)+1,3) + --AS REGIMEN,
				SUBSTRING(TXRGNNUM,1,11) + --as CUIT_RETENIDO +
				REPLACE(CONVERT(char(10),nfRET_Fec_Retencion,105),'-','/') + --AS FECHA_RETENCION +
				'06' + --TIPO COMPROBANTE
				REPLACE(CONVERT(char(10),PM.DOCDATE,105),'-','/') + --AS FECHA_COMPROBANTE +
				LEFT(RTRIM(R.DOCNUMBR) + REPLICATE(' ',16) ,16) + --NOR COMPROBANTE
				RIGHT(REPLICATE('0',14)+ RTRIM(CONVERT(char(14),CONVERT(NUMERIC(14,2),nfRET_Base_Calculo))),14) +  --IMPORTE COMPROBANTE
				RIGHT(REPLICATE('0',14)+ RTRIM(CONVERT(char(14),CONVERT(NUMERIC(14,2),nfRET_Importe_Retencion))),14)+ ';', --IMPORTE RETENCION
				REPLICATE(' ',25) + --CERTIFICADO ORIGINAL NRO
				REPLICATE(' ',10) + -- CERTIFICADO ORIGINAL FECHA RETEN
				REPLICATE(' ',14) + -- CERTIFICADO ORIGINAL IMPORTE
				REPLICATE(' ',30) + ';'--OTROS DATOS
		FROM	TLSUS001 T 
				INNER JOIN nfRET_GL10020 R ON T.ID_Retencion = R.nfRET_Retencion_ID 
				INNER JOIN PM00200 V ON R.VENDORID = V.VENDORID
				INNER JOIN PM30200 PM ON PM.DOCTYPE = R.DOCTYPE AND PM.VCHRNMBR = R.VCHRNMBR
				LEFT OUTER JOIN nfRET_GL00030 RG ON RG.nfRET_Retencion_ID = R.nfRET_Retencion_ID ,
				DYNAMICS..SY01500 CMP 
		WHERE  CMP.INTERID = DB_NAME()
		AND nfRET_Fec_Retencion >= @StartDate AND nfRET_Fec_Retencion <= @EndDate and nfRET_Importe_Retencion <>0 
	END
	ELSE
	BEGIN
		SELECT	--'2005' + -- AS FORMULARIO 
				'0100' + -- AS VERSION +
				REPLICATE(' ',36) + --AS CODIGO_TRAZABILIDAD +
				substring(Rg.nfRET_Regimen,1,charindex('-',Rg.nfRET_Regimen)-1)  + --AS IMPUESTO,
				substring(Rg.nfRET_Regimen,charindex('-',Rg.nfRET_Regimen)+1,3) + --AS REGIMEN,
				REPLACE(CONVERT(char(10),nfRET_Fec_Retencion,105),'-','/') + --AS FECHA_RETENCION +
				'  ' +-- CONDICION 0/1
				'0' + -- IMPOSIBILIDAD de RETENCION VACIO 1
				REPLICATE(' ',30) + --NO RETENCIÓN MOTIVO
				RIGHT(REPLICATE('0',14)+ RTRIM(CONVERT(char(14),CONVERT(NUMERIC(14,2),nfRET_Importe_Retencion))),14)+ -- IMPORTE RETECNCION
				RIGHT(REPLICATE('0',14)+ RTRIM(CONVERT(char(14),CONVERT(NUMERIC(14,2),nfRET_Base_Calculo))),14) + -- BASE DE CALCULO
				'0' + --REGIMEN EXCLUSION 1 
				REPLICATE(' ',6) + --PORCENTAJE EXCLUSION
				REPLICATE(' ',10) + --FECHA PUBLICACION O FINALIZACION 
				'01' + --TIPO COMPROBANTE
				REPLACE(CONVERT(char(10),PM.DOCDATE,105),'-','/') + --AS FECHA_COMPROBANTE +
				LEFT(RTRIM(SUBSTRING(PM.DOCNUMBR,4,100)) + REPLICATE(' ',16) ,16) + --NOR COMPROBANTE
				REPLICATE(' ',12) + --COE
				REPLICATE(' ',12) + --COE ORIGINAL
				REPLICATE(' ',14) + -- CAE
				RIGHT(REPLICATE('0',14)+ RTRIM(CONVERT(char(14),CONVERT(NUMERIC(14,2),PM.DOCAMNT))),14) + ';', -- IMPORTE COMPROBANTE
				--SEparo los String porque no soporta Dex + de 255
				REPLICATE(' ',30) + -- MOTIVO EMISION NOTA
				SUBSTRING(TXRGNNUM,1,11) + --as RETENIDO CLAVE +
				REPLICATE(' ',25) + --CERTIFICADO ORIGINAL NRO
				REPLICATE(' ',10) + -- CERTIFICADO ORIGINAL FECHA RETEN
				REPLICATE(' ',14) + -- CERTIFICADO ORIGINAL IMPORTE
				REPLICATE(' ',1)  + ';'-- MOTIVO ANULACION
		FROM	TLSUS001 T 
				INNER JOIN nfRET_GL10020 R ON T.ID_Retencion = R.nfRET_Retencion_ID 
				INNER JOIN PM00200 V ON R.VENDORID = V.VENDORID
				INNER JOIN PM30200 PM ON PM.DOCTYPE = R.DOCTYPE AND PM.VCHRNMBR = R.VCHRNMBR
				LEFT OUTER JOIN nfRET_GL00030 RG ON RG.nfRET_Retencion_ID = R.nfRET_Retencion_ID,
				DYNAMICS..SY01500 CMP 
		WHERE  CMP.INTERID = DB_NAME()
		AND nfRET_Fec_Retencion >= @StartDate AND nfRET_Fec_Retencion <= @EndDate and nfRET_Importe_Retencion <>0 
	END
END

GO


